---
# tasks file for install-python
- name: Install python3
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: Install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Make pip3 as default pip
  command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10

- name: Make python3 as default python
  command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
